api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns =[
    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getProject),
    path('projects/<str:pk>/vote/', views.projectVote),
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('remove-tag/', views.removeTag),
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

new/bba/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include,re_path
# from django.conf.urls import re_path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bba_admin.urls')),
    path('api/', include('bba_admin_api.urls')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),
    path('account/', views.userAccount, name='account'),
    path('edit-account/', views.editAccount, name='edit-account'),
    path('create-skill/', views.createSkill, name='create-skill'),
    path('update-skill/<str:pk>/', views.updateSkill, name='update-skill'),
    path('delete-skill/<str:pk>/', views.deleteSkill, name='delete-skill'),
    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name='create-message'),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.



class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created']
        
    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ''
            
        return url
        
                
        
        
    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes= reviews.filter(value='up').count()
        totalVotes = reviews.count()
        ratio= (upVotes / totalVotes) * 100
        
        self.vote_ratio = ratio
        self.vote_total = totalVotes
        self.save()
    
    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list("owner__id", flat=True)
        return queryset        
    
   
    
    
class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete = models.CASCADE)
    body  = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    class Meta:
        unique_together =[['owner', 'project']]
    
    def __str__(self):
        return self.value
    
class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True,blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)


    def __str__(self):
        return str(self.user.username)

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''

        return url


    class Meta:
        ordering = ['created']


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    sender= models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient= models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']

        labels ={
            'first_name': 'Name',
        }
        
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})
            
            
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
            
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})
        
        
class SkillForm(ModelForm):
    class Meta:
        model = Skill
        exclude = ('owner',)
            
    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})        
            
            

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

        
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

new/bba_admin/views/user_profile_view.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib import messages
from bba_admin.models import (Enquiry, LocationWebsite, Employee)
import logging
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes  
from django.contrib.sites.shortcuts import get_current_site
# Create your views here.

logger = logging.getLogger(__name__)


def user_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(username=email)
        except:
            messages.error(request, "Email does not exist")
            return render(request, 'login.html')
        
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)

            return redirect('dashboard')
        else:
            messages.error(request, "Username or Password is incorrect")
            return redirect('user-login')
        
    return render(request, 'accounts/login.html')

@login_required(login_url='user-login')
def user_logout(request):
    logout(request)
    return redirect('user-login')


@login_required(login_url='user-login')
def dashboard(request):
    loc_web_count = LocationWebsite.objects.filter(status="Active", deleted=False).count()
    admin_users_count = Employee.objects.filter(status="Active").count()
    enquiry_count = Enquiry.objects.all().count()
    enquiry = Enquiry.objects.all().order_by('-id')[:10]
    context = {
        'enquiry_list': enquiry,
        'loc_web_count': loc_web_count,
        'admin_users_count': admin_users_count,
        'enquiry_count': enquiry_count
    }
    return render(request, 'dashboard.html', context)


def recover_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        if User.objects.filter(email=email, username=email).exists():
            user = User.objects.get(email__iexact=email)

            current_site = get_current_site(request)
            mail_subject = "Reset Password"
            data = {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user)
            }
            message = render_to_string('accounts/reset_password_email.html', data)
            to_email = email
            send_mail = EmailMessage(mail_subject, message, to=[to_email])
            send_mail.send()
            messages.success(request,"Password reset email has been sent to your email address")
            return redirect('user-login')
        else:
            messages.error(request, "Account does not exist")
            return redirect('recover-password')
        
    return render(request, 'accounts/recover-password.html', {})


def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except:
        if user is not None and default_token_generator.check_token(user, token):
            request.session['uid'] = uid
            messages.success(request, "Please reset your password")
            return redirect('reset-password')
        else:
            messages.error(request, "the link has been expired")
            return redirect('user-login')
        

def reset_password(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password == confirm_password:
            uid = request.session.get('uid')
            user = User.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, "Password reset successfully")
            return redirect('user-login')
        else:
            messages.error(request, "Password does not match")
            return redirect('reset-password')
        
    return render(request, 'accounts/reset-password.html')

        

users/templates/users/account.html
{% extends 'main.html'%} {% block content %}

<!-- Main Section -->
<main class="settingsPage profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
                        <img class="avatar avatar--xl dev__avatar"
                            src="{{profile.imageURL}}" />
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">
                            {{profile.short_intro}}
                        </p>
                        <p class="dev__location">{{profile.location}}</p>
                        <ul class="dev__social">
                            {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{profile.social_github}}" target="_blank"><i
                                        class="zmdi zmdi-github zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_youtube %}
                            <li>
                                <a title="Youtube" href="{{profile.social_youtube}}" target="_blank"><i
                                        class="zmdi zmdi-youtube zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_twitter %}
                            <li>
                                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i
                                        class="zmdi zmdi-twitter zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_linkedin %}
                            <li>
                                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i
                                        class="zmdi zmdi-linkedin zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i
                                        class="zmdi zmdi-google zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">
                        {{profile.bio}}
                    </p>
                </div>
                <div class="settings">
                    <h3 class="settings__title">Skills</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add
                        Skill</a>
                </div>

                <table class="settings__table">
                    {% for skill in skills%}
                    <tr>
                        <td class="settings__tableInfo">
                            <h4>{{skill.name}}</h4>
                            <p>
                                {{skill.description}}
                            </p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i>
                                Edit</a>
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i
                                    class="im im-x-mark-circle-o"></i> Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                   
                </table>

                <div class="settings">
                    <h3 class="settings__title">Projects</h3>
                    <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add
                        Project</a>
                </div>

                <table class="settings__table">
                    {% for project in projects %}
                    <tr>
                        <td class="settings__thumbnail">
                            <a href="{% url 'project' project.id %}"><img src="{{project.imageURL}}" alt="Project Thumbnail" /></a>
                        </td>
                        <td class="settings__tableInfo">
                            <a href="{% url 'project' project.id %}">{{project.title}}</a>
                            <p>
                                {{project.description|slice:"150"}}
                            </p>
                        </td>
                        <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i>
                                Edit</a>
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"><i
                                    class="im im-x-mark-circle-o"></i> Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
        {%for message in messageRequests %}
        {% if message.is_read == False %}
        <li class="message message--unread">
        {% else %}
        <li class="message">
        {% endif %}

          <a href="{% url 'message' message.id %}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>
        {% endfor %}
       
      </ul>
    </div>
  </main>

{% endblock %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{message.subject}}</h4>
          {% if message.sender %}
          <a href="{% url 'user-profile' message.sender.id %}" class="message__author">{{message.name}}</a>
          {% else %}
          <p class="message__author">{{message.name}}</p>
          {% endif %}
          <p class="message__date">{{message.created}}</p>
          <div class="message__body">
            {{message.body|linebreaksbr}}
          </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">
                <form class="form" action="#" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers </label>
                        <input class="input input--text" id="formInput#search" type="text" name="text"
                            placeholder="Search by developer name" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">
                {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'user-profile' profile.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{profile.profile_image.url}}"
                                    alt="image" />
                                <div class="dev__meta">
                                    <h3>{{profile.name}}</h3>
                                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                                </div>
                            </div>
                            <p class="dev__info">
                                {{profile.bio|slice:"150"}}
                            </p>
                            <div class="dev__skills">
                                {% for skill in profile.skill_set.all|slice:"5" %}
                                <span class="tag tag--pill tag--main">
                                    <small>{{skill}}</small>
                                </span>
                                {% endfor %}
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
                
                
            </div>
        </div>
    </section>

</main>

{% endblock %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{profile.imageURL}}" />
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">{{profile.short_intro}}</p>
                        <p class="dev__location">Based in {{profile.location}}</p>
                        <ul class="dev__social">
                            {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{profile.social_github}}" target="_blank"><i
                                        class="zmdi zmdi-github zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_youtube %}
                            <li>
                                <a title="Youtube" href="{{profile.social_youtube}}" target="_blank"><i
                                        class="zmdi zmdi-youtube zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_twitter %}
                            <li>
                                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i
                                        class="zmdi zmdi-twitter zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_linkedin %}
                            <li>
                                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i
                                        class="zmdi zmdi-linkedin zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i
                                        class="zmdi zmdi-google zmdi-hc-2x"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                        {% if request.user.profile.id != profile.id %}
                        <a href="{% url 'create-message' profile.id  %}" class="btn btn--sub btn--lg">Send Message </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">
                        {{profile.bio}}
                    </p>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Skills</h3>
                    <div class="devInfo__skills">
                        {% for skill in topSkills %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{ skill.name }}</h4>
                            <p class="devSkill__info">
                                {{skill.description}}
                            </p>
                        </div>
                        {% endfor %}



                        <h3 class="devInfo__subtitle">Other Skills</h3>
                        <div class="devInfo__otherSkills">
                            {% for skill in otherSkills %}
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>{{skill.name}}</small>
                            </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Projects</h3>
                    <div class="grid grid--two">
                        {% for project in profile.project_set.all%}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'project' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{project.imageURL}}"
                                        alt="project thumbnail" />
                                    <div class="card__body">
                                        <h3 class="project__title">{{project.title}}</h3>
                                        <p><a class="project__author" href="profile.html">By {{project.owner.name}}</a>
                                        </p>
                                        <p class="project--rating">
                                            <span style="font-weight: bold;">92%</span> Postitive
                                            Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                                        </p>
                                        <div class="project__tags">
                                            {% for tag in project.tags.all %}
                                            <span class="tag tag--pill tag--main">
                                                <small>{{tag}}</small>
                                            </span>
                                            {% endfor %}

                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}




                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}